dubbo:
  application:
    name: ${spring.application.name}

  registry:
    address: nacos://${spring.cloud.nacos.server-addr:127.0.0.1:8848}
#    register-mode: all
  protocol:
    name: dubbo
    port: -1

#  consumer:
#    validation: jvalidationNew

#Loggiong
logging:
  level:
    org.springframework.security: debug
    org:
      springframework:
        boot:
          web:
            embedded:
              tomcat:
                TomcatEmbeddedWebappClassLoader: DEBUG




spring:
  profiles:
    include: data
#Sentinel
  cloud:
    sentinel:
      transport:
        dashboard: http://127.0.0.1:8080
      eager: true
      web-context-unify: true
      datasource:
        d1:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}



#monitor
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 19999

#  metrics:
#    distribution:
#      percentiles: 0.5,0.75,0.95,0.99
#      percentiles-histogram: true
#      slo: 0.1,0.3,0.5,1,3





