dubbo:
  application:
    name: ${spring.application.name}

  registry:
    address: nacos://${spring.cloud.nacos.server-addr:127.0.0.1:8848}
    register-mode: instance
  protocol:
    name: dubbo
    port: -1
#  consumer:
#    validation: jvalidationNew
  provider:
    filter: tracing


spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://172.31.231.195:3306/casclient?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
        username: groupone
        password: eK7xL8lY3eK9

    rules:
      sharding:
        tables:
          test:
            actual-data-nodes: ds0.test_0$->{1..2}
            tableStrategy:
              standard:
                sharding-algorithm-name: test_inline
                sharding-column: id
            key-generate-strategy:
              column: id
        sharding-algorithms:
          test_inline:
            type: inline
            props:
              algorithm-expression: test_0$->{id % 2 + 1}


  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1

server:
  port: 8888


# zipkin图形展现地址和采样率设置
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 #采样率默认为0.1(0.1就是10次只能有一次被记录下来)，值越大收集越及时。


logging:
  level:
    org.springframework.web: debug




