spring:
  datasource:
    db0:
      type: com.alibaba.druid.pool.DruidDataSource
      jdbc-url: jdbc:mysql://
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: abc
      password: 123
    db1:
      jdbc-url: jdbc:mysql://111
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: abc111
      password: 123111
    url: jdbc:mysql://111
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: abc111
    password: 123111