server:
  port: 8787


spring:
  application:
    name: cloud-service-gateway
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      metrics:
        enabled: true
        tags:
          path:
            enabled: true
      routes:
        - id: cloud-service-consumer
          predicates:
            - Path=/consumer/**
          uri: http://localhost:9999
        - id: cloud-service-provider
          predicates:
            - Path=/provider/**
          uri: http://localhost:8888
          filters:
            - AddRequestHeader=X-Request-red, blue
      default-filters:
        - AddRequestHeader=X-Request-red, blue


#monitor
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 18888