spring:
  application:
    name: eureka-server
server:
  port: 8899

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8899/eureka

  instance:
    metadata-map:
      test-key: "aaa"